server:
  port: 8082
spring:
  devtools:
    restart:
      exclude:  static/**,public/**
      enabled:  true
  datasource:
    name: sv
    url: jdbc:mysql://localhost:3306/ligh?useUnicode=true&characterEncoding=utf8
    username: ipp
    password: ipp
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml