server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://172.17.130.76:3306/jdbc
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml