server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://172.17.130.76:3306/test
    username: test
    password: test
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml